FROM alpine:latest

RUN apk add --no-cache --update python3-dev gcc g++ autoconf make libffi-dev openssl-dev dumb-init py3-openssl
RUN pip3 install --no-cache-dir salt=={{salt_version}} pycryptodomex CherryPy

RUN addgroup -S salt && adduser -SD -G salt salt && \
    mkdir -p /etc/pki /etc/salt/master.d /var/cache/salt /var/log/salt /var/run/salt && \
    chmod -R 2775 /etc/pki /etc/salt /var/cache/salt /var/log/salt /var/run/salt && \ 
    chgrp -R salt /etc/pki /etc/salt /var/cache/salt /var/log/salt /var/run/salt

USER salt
RUN salt-run salt.cmd tls.create_self_signed_cert

ENTRYPOINT ["/usr/bin/dumb-init"]
CMD ["--", "/usr/local/bin/saltinit"]
ADD saltinit.py /usr/local/bin/saltinit
EXPOSE 8000
